### ISSUE TITLE
Enforce "has-accessibility-props" on `Pressable`

### ISSUE THREAD

**Issue by caass** [FormidableLabs/eslint-plugin-react-native-a11y#110]
[`Pressable`](https://reactnative.dev/docs/pressable) is the preferred API to [`Touchable`](https://reactnative.dev/docs/touchablehighlight), it would be nice to have this linting rule also apply to `Pressable` components as well.

**Comment by jpdriver** [comment]
hey @caass 

`Pressable` is [already considered](https://github.com/FormidableLabs/eslint-plugin-react-native-a11y/blob/master/src/util/isTouchable.js#L11-L19) one of the `defaultTouchables`. If you've noticed an issue with a particular rule and `Pressable`, please feel free to open another issue.

thanks!
