### ISSUE TITLE
Unable to resolve dependency tree

### ISSUE THREAD

**Issue by RodrigoNovais** [FormidableLabs/eslint-plugin-react-native-a11y#114]
I tried to install the package as described on npm
`npm install eslint-plugin-react-native-a11y --save-dev`
and got stucked with this error

![oie_koHFcyykeLBX](https://user-images.githubusercontent.com/11841314/115262298-cb732d00-a10a-11eb-9cd7-41a2e559cc05.png)

I'm using Expo-CLI to setup this project
Other Eslint libraries are working so far

![oie_uFw1bNLdgCkk](https://user-images.githubusercontent.com/11841314/115263604-ef833e00-a10b-11eb-809f-67fc008566c9.png)

**Comment by ryanhyslop** [comment]
Anyone else gets this its fixed here: https://github.com/FormidableLabs/eslint-plugin-react-native-a11y/pull/111 but doesn't look like we have a tagged version with this so will have to install from that commit instead.

**Comment by jpdriver** [comment]
hey all 👋🏻 just published `eslint-plugin-react-native-a11y@3.0.0` which includes the changes from #111

should resolve this issue, please feel free to reopen if you're still having problems. cheers!
