### ISSUE TITLE
Getting a warning even when passing AccessibilityState as an object

### ISSUE THREAD

**Issue by Kamalnrf** [FormidableLabs/eslint-plugin-react-native-a11y#121]
```
const accessibilityState: AccessibilityState =
      disabled !== props.accessibilityState?.disabled
        ? {...props.accessibilityState, disabled, busy: loading}
        : {...props.accessibilityState, busy: loading}
```

This is how we are computing the accessibility state in a component. We see a warning triggered by `react-native-a11y/has-valid-accessibility-state` saying the passed value is not an object in the attached screenshot. 

![Screen Shot 2021-07-01 at 16 35 11](https://user-images.githubusercontent.com/12810203/124114784-9d0aba00-da8a-11eb-9645-01b14c1b896f.png)

When we change the prop value to an empty object `{}` the warning seems to go away. Still, changing the `accessibilityState` variable value to an empty object, we see the warning again. 

```
const accessibilityState = {}
```

The expected behavior is that we shouldn't see this warring as the value of `accessibilityState` is an object in both snippets.

**Comment by lukewalczak** [comment]
Hey @Kamalnrf, since you closed the issue, could you please share, what was the root of the problem or how did you solve it?

**Comment by jpdriver** [comment]
should no longer be an issue with https://github.com/FormidableLabs/eslint-plugin-react-native-a11y/pull/129 / `v3.2.0` or newer
