### ISSUE TITLE
Support ESLint 8

### ISSUE THREAD

**Issue by robrechtme** [FormidableLabs/eslint-plugin-react-native-a11y#137]
Hi 👋🏻 

Could you check if this plugin still works on ESLint 8 and, if so, update the [peer dependencies](https://github.com/FormidableLabs/eslint-plugin-react-native-a11y/blob/master/package.json#L64) to support it? Many thanks 🙏🏻 

I tested it out on ESLint 8 and in my project, there were no issues.

**Comment by jpdriver** [comment]
hey @robrechtme -- we're trying to track the version `react-native` supports out of the box, which for right now is set to `eslint@7`

> see https://github.com/facebook/react-native/blob/v0.67.4/template/package.json#L21

if a later release of RN support ESLint 8, we'll bump this plugin to match.
