### ISSUE TITLE
Adding eslint 8 as compatible peer dependency

### ISSUE THREAD

**Issue by philihp** [FormidableLabs/eslint-plugin-react-native-a11y#144]
```
warning " > eslint-plugin-react-native-a11y@3.2.1" has incorrect peer dependency "eslint@^3 || ^4 || ^5 || ^6 || ^7".
```

Any blockers on adding eslint 8?

**Comment by trevorrd** [comment]
Has there been any update on this yet? I'm trying to get this installed for a react-native project for work but since this doesn't allow eslint 8, it's not letting me install it.
