### ISSUE TITLE
Add links to rule definitions in rule error messages

### ISSUE THREAD

**Issue by jevakallio** [FormidableLabs/eslint-plugin-react-native-a11y#23]
Consider error message like:

```
const errorMessage = 'accessibilityComponentType must be one of defined values'
```

If I get this error, I won't have any idea what the defined values are.

However, if the error message were something like:

```
const errorMessage = `accessibilityComponentType value is not valid. 

See valid values: https://github.com/FormidableLabs/eslint-plugin-react-native-a11y/blob/master/docs/rules/has-valid-accessibility-component-type.md`
```

Then it would be easier to check what the valid values are.

**Comment by jpdriver** [comment]
https://github.com/FormidableLabs/eslint-plugin-react-native-a11y/pull/77#issuecomment-612020281
