### ISSUE TITLE
Support new accessibility API in RN 0.57

### ISSUE THREAD

**Issue by thymikee** [FormidableLabs/eslint-plugin-react-native-a11y#35]
React Native overhauls the accessibility API, would be great to support it (it's currently in RC phase).

Here's a detailed blog post about the changes: http://facebook.github.io/react-native/blog/2018/08/13/react-native-accessibility-updates

Not sure which solution makes more sense: introducing the support as a major release or adding extra rule/preset.

BTW, thanks for working on this plugin :)

**Comment by satya164** [comment]
I think it should be in the same version for some time before removing the old ones and let us selectively enable/disable the ones we want. It'll be useful for UI libs and will help with gradually upgrading the code.

We have both in react-native-paper to support old and new versions of RN and planning to use this plugin.

**Comment by draperunner** [comment]
@knitcodemonkey When will v1.1.0 be published on NPM? v1.0.0 is still the latest version.

**Comment by knitcodemonkey** [comment]
@draperunner v1.1.0 has now been published. It does not include all the latest features added by 0.57, but its a start.

**Comment by AryanJ-NYC** [comment]
First off, just want to thank FormidableLabs for the awesome work. Just a quick question:

When is the next publish planned? I ask because https://github.com/FormidableLabs/eslint-plugin-react-native-a11y/pull/54 got merged but I'm still getting an error when using `accessibilityRole='alert'` (and I checked https://www.npmjs.com/package/eslint-plugin-react-native-a11y and saw the last publish was nine months ago).

There's no rush but just curious!

**Comment by alex-saunders** [comment]
Hi @AryanJ-NYC , I'm planning to do a release soon, just getting that 1 outstanding PR merged first.
Hopefully not too long!

**Comment by AryanJ-NYC** [comment]
Hey @alex-saunders. Is https://github.com/FormidableLabs/eslint-plugin-react-native-a11y/pull/48 the outstanding PR that needs to be merged first? If so, it looks like it's ready for another look.

**Comment by jpdriver** [comment]
the more modern Accessibility APIs are now officially supported as of [v2.0.0](https://github.com/FormidableLabs/eslint-plugin-react-native-a11y/releases/tag/v2.0.0)
