### ISSUE TITLE
The accessibilityStates does not allow an empty state.

### ISSUE THREAD

**Issue by fawcilize** [FormidableLabs/eslint-plugin-react-native-a11y#45]
According to the documentation, https://facebook.github.io/react-native/docs/view#accessibilitystates: `You can provide one state, no state, or both states`. This is the case when a button may be unselected and enabled, like an inactive tab.

**Comment by jpdriver** [comment]
fixed with [v1.3.0](https://github.com/FormidableLabs/eslint-plugin-react-native-a11y/releases/tag/v1.3.0)
