### ISSUE TITLE
Should support all valid accessibilityStates

### ISSUE THREAD

**Issue by renaekathleen** [FormidableLabs/eslint-plugin-react-native-a11y#49]
React Native now supports additional accessibilityStates (https://facebook.github.io/react-native/docs/accessibility.html#accessibilitystates-ios-android), which this should support. Furthermore, it should support an empty state, which is helpful for when the accessibilityStates are programmatically determined https://github.com/FormidableLabs/eslint-plugin-react-native-a11y/issues/45

**Comment by jpdriver** [comment]
fixed with [v1.3.0](https://github.com/FormidableLabs/eslint-plugin-react-native-a11y/releases/tag/v1.3.0)
