### ISSUE TITLE
Deprecate accessibilityStates in favour of accessibilityState?

### ISSUE THREAD

**Issue by VirtualDOMinic** [FormidableLabs/eslint-plugin-react-native-a11y#76]
From the latest docs (somewhat confusingly on the [`View` component API page since **version 0.60**](https://facebook.github.io/react-native/docs/0.60/view) and the [Accessibility guide since **version 0.59**](https://facebook.github.io/react-native/docs/0.59/accessibility)), `accessibilityState` replaces `accessibilityStates`. It is now an object with several options instead of an array of two possible strings.

It's not quite clear whether `accessibilityStates` will still work though.

Either way, `has-valid-accessibility-state` rule, docs and tests need to be updated to handle this.

**Comment by VirtualDOMinic** [comment]
Update, turns out it's addressed by PR #60 (not yet merged) ! Nice @jpdriver

**Comment by jpdriver** [comment]
see linked PR for more details & discussion
