### ISSUE TITLE
accessibilityState doesn't recognise boolean value in variable

### ISSUE THREAD

**Issue by zvona** [FormidableLabs/eslint-plugin-react-native-a11y#84]
Following code throws an error: _"accessibilityState object: "selected" value is not a boolean"_
```
interface Props {
  active: boolean;
}

const C: React.SFC<Props> = ({
  active,
}) => (
  <TouchableHighlight
    accessibilityState={{
      selected: active,
    }}
  >
  ...
);
```

If I replace `active` with true/false, it passes.

**Comment by zvona** [comment]
One way to fix this is to reassure it's a boolean by: `selected: !!active`, but I don't know whether this is a  permanent way to fix it.

**Comment by jpdriver** [comment]
hey @zvona -- thank you so much for raising this bug. I've just published a new release that includes a workaround detailed in the PR linked above. Please try it out 😄 
```
yarn add eslint-plugin-react-native-a11y@2.0.0-rc1
```

**Comment by arjunu** [comment]
Same issue exists with `accessibilityStates`:

```
 <TouchableHighlight
    accessibilityStates={props.disabled? ["disabled"]: []}
/>
```

doesn't work.
