### ISSUE TITLE
accessibilityState doesn't recognize boolean value in checked variable

### ISSUE THREAD

**Issue by reedwilliams24** [FormidableLabs/eslint-plugin-react-native-a11y#97]
Building off of [this previous issue](https://github.com/FormidableLabs/eslint-plugin-react-native-a11y/issues/84) that was fixed in https://github.com/FormidableLabs/eslint-plugin-react-native-a11y/pull/85.

```
const itemChecked = true;

...

<TouchableHighlight accessibilityState={{ checked: itemChecked }} /> // error
<TouchableHighlight accessibilityState={{ selected: itemChecked }} /> // no error
```

Looks like [this check](https://github.com/FormidableLabs/eslint-plugin-react-native-a11y/pull/85/files#diff-c10eeadd8939ba1696b358027e68f430R59) needs to be added around [this error](https://github.com/FormidableLabs/eslint-plugin-react-native-a11y/blob/master/src/rules/has-valid-accessibility-state.js#L46) as well.

**Comment by jpdriver** [comment]
hey @reedwilliams24 -- thank you so much for raising this bug. I've just published a [new release](https://github.com/FormidableLabs/eslint-plugin-react-native-a11y/releases/tag/v2.0.2) that includes a fix for this.

**Comment by reedwilliams24** [comment]
No problem @jpdriver - thanks for the quick fix.
